apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-assignment
spec:
  selector:
    matchLabels:
      app: docker-assignment
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-assignment
    spec:
      containers:
        - name: docker-assignment
          image: innomight/docker-assignment.jar
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090